{{- if and .Values.postgres.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canvas.postgresSecretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "canvas.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}
