# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
services:
  web: &WEB
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: sekret
    ports:
      - "127.0.0.1:80:80"   # only reachable on localhost port 80

  jobs:
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: sekret
    command: bundle exec script/delayed_job run

  postgres:
    build: ./docker-compose/postgres
    environment:
      POSTGRES_PASSWORD: sekret
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:alpine
